# the interesting tags listed under a ReportItem with severity above 0
report_item_tags = {'pluginName',
                    'cve',
                    'cvss3_base_score',
                    'cvss_base_score',
                    'cvss3_vector',
                    'cvss_vector',
                    'cvss3_temporal_vector',
                    'cvss_temporal_vector',
                    'patch_publication_date',
                    'description',
                    'exploit_available',
                    'exploitability_ease',
                    'see_also',
                    'solution',
                    'plugin_output'}

# tag - the XML field where the value is, overrides 'value' if provided
# value - mutually exclusive with 'tag', provides the value directly
# key - the key under which the extracted data is stored in the results dict
# [parent|sub]key - a crutch to help store some more awkward data
# yields - how to store the data in db (table.field)
# re - optional, the regexp to apply to the tag contents before storing
# port and protocol are always added for all elements
info_plugins = { 'Additional DNS Hostnames':                {   'tag': 'plugin_output',
                                                                'key': 'virthost',
                                                                'yields': 'http_virthost.virthost',
                                                                're': 'hostnames point to the remote host\s+:\s+-\s([a-z0-9\.]+)'},
                 # picks up backports and overrides version
                 'Apache HTTP Server Version':              {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                'yields': 'services.software',
                                                                'prefix': 'Apache ',
                                                                're': 'Version\s+:\s+([0-9\.]+)'},
                 'Check_MK Agent Detection':                {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                'yields': 'services.software',
                                                                'prefix': 'Check_MK Agent ',
                                                                're': 'version\s+:\s+([A-Za-z0-9\.]+)'},
                 'IPSEC Internet Key Exchange (IKE) Version 1 Detection': {   'value': 'IPSEC IKE v1',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'IPSEC Internet Key Exchange (IKE) Version 2 Detection': {   'value': 'IPSEC IKE v2',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'WebDAV Detection':                        {   'value': 'WebDAV',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'SolarWinds Server & Application Monitor (SAM) Detection': {   'value': 'SolarWinds',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Inconsistent Hostname and IP Address':    {   'tag': 'plugin_output',
                                                                'key': 'bad_fqdn',
                                                                're': "\'([A-Za-z0-9\./-]+)\' does not resolve",
                                                                'yields': None},
                 'Open Port Re-check':                      {   'tag': 'plugin_output',
                                                                'key': 'errors',
                                                                'yields': 'services.errors'},
                 'Broken Web Servers':                      {   'tag': 'plugin_output',
                                                                'key': 'errors',
                                                                're': 'reason\s:\s([a-zA-Z\s\.]+)',
                                                                'yields': 'services.errors'},
                 'CGI Generic Tests HTTP Errors':           {   'tag': 'plugin_output',
                                                                'key': 'errors',
                                                                'yields': 'services.errors'},
                 'Web Application Sitemap':                 {   'tag': 'plugin_output',
                                                                'key': 'sitemap',
                                                                're': '(https?://[a-zA-Z0-9\./-]+)',
                                                                'yields': 'services.sitemap'},
                 'Web Server Directory Enumeration':        {   'tag': 'plugin_output',
                                                                'key': 'web_dir_enum',
                                                                'yields': 'services.web_dir_enum'},
                 'Web mirroring':                           {   'tag': 'plugin_output',
                                                                'key': 'cgi_enum',
                                                                'yields': 'services.cgi_enum'},
                 'phpMyAdmin Detection':                    {   'tag': 'plugin_output',
                                                                'key': 'phpmyadmin',
                                                                're':  'Version\s+:\s+([0-9\.]+)',
                                                                'prefix': 'phpMyAdmin v',
                                                                'yields': 'services.phpmyadmin'},
                 'Web Server Harvested Email Addresses':    {   'tag': 'plugin_output',
                                                                'key': 'email_harvest',
                                                                'yields': 'services.email_harvest'},
                 'Web Server No 404 Error Code Check':      {   'value': True,
                                                                'key': 'no404sent',
                                                                'yields': 'services.no404sent'},
                 'PHP Version Detection':                   {   'tag': 'plugin_output',
                                                                'key': 'php_version',
                                                                'prefix': 'PHP ',
                                                                're': "Version\s+:\s+([0-9\.]+)",
                                                                'yields': 'services.php_version'},
                 'Apache Tomcat Detection':                 {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                'prefix': 'Apache Tomcat ',
                                                                're': "Version\s+:\s+([0-9\.]+)",
                                                                'yields': 'services.software'},
                 'CGI Generic Injectable Parameter':        {   'tag': 'plugin_output',
                                                                'key': 'injectable_param',
                                                                'yields': 'services.injectable_param'},
                 'Drupal Software Detection':               {   'tag': 'plugin_output',
                                                                'key': 'drupal_detected',
                                                                'yields': 'services.drupal_detected'},
                 'Python Remote HTTP Detection':            {   'tag': 'plugin_output',
                                                                'key': 'python_detected',
                                                                'yields': 'services.python_detected'},
                 'Microsoft .NET Handlers Enumeration':     {   'tag': 'plugin_output',
                                                                'key': 'dotnet_handlers',
                                                                'yields': 'services.dotnet_handlers'},
                 'Embedded Web Server Detection':           {   'value': True,
                                                                'key': 'embedded_server',
                                                                'yields': 'services.embedded_server'},
#                 'SSL / TLS Versions Supported':            {   'tag': 'plugin_output',
#                                                                'key': 'tls_supported',
#                                                                're': "This port supports\s+(.*)$",
#                                                                'yields': 'services.tls_supported'},
                 'Palo Alto Networks PAN-OS Firewall/Panorama Web UI Detection': {'value': 'Palo Alto WebUI',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'SSH Protocol Versions Supported':         {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                're': "-\s([0-9\.]+)",
                                                                'prefix': 'SSH ',
                                                                'yields': 'services.software'},
                 'SSL Certificate Information':             {   'tag': 'plugin_output',
                                                                'key': 'cert_cn',
                                                                're': 'Common Name:\s+([a-zA-Z][A-Za-z0-9\.-]+)',
                                                                'yields': 'services.cert_cn'},
                 'CGI Generic Tests Timeout':               {   'tag': 'plugin_output',
                                                                'key': 'errors',
                                                                'yields': 'services.errors'},
                 'Web Server / Application favicon.ico Vendor Fingerprinting':       {   'tag': 'plugin_output',
                                                                'key': 'software_favicon',
                                                                're': 'Web server\s*:\s*([a-zA-Z].*)$',
                                                                'yields': 'services.software_favicon'},
                 'Web Server robots.txt Information Disclosure':                     {   'tag': 'plugin_output',
                                                                'key': 'robots_txt',
                                                                'yields': 'services.robots_txt'},
                 'ArubaOS Detection':                       {   'tag': 'plugin_output',
                                                                're': 'Model\s+:\s+([a-zA-Z0-9 -]+)',
                                                                'key': 'os',
                                                                'yields': 'hosts.os'},
                 'Do not scan printers (AppSocket)':        {   'value': 'network printer',
                                                                'key': 'os',
                                                                'yields': 'hosts.os'},
                 'Do not scan printers':                    {   'value': 'network printer',
                                                                'key': 'os',
                                                                'yields': 'hosts.os'},
                 'Do not scan operational technology devices': { 'value': 'operational technology device',
                                                                'key': 'os',
                                                                'yields': 'hosts.os'},
                 'Reverse NAT/Intercepting Proxy Detection': {  'value': 'firewall/proxy',
                                                                'key': 'os',
                                                                'yields': 'hosts.os'},
                 'Wireless Access Point Detection':         {   'value': 'Wireless Access Point',
                                                                'key': 'os',
                                                                'yields': 'hosts.os'},
                 'HP Switch Identification':                {   'value': 'HP Switch',
                                                                'key': 'os',
                                                                'yields': 'hosts.os'},
                 'VMware Virtual Machine Detection':        {   'value': 'VMware Virtual Host',
                                                                'key': 'os',
                                                                'yields': 'hosts.os'},
                 'LPD Detection':                           {   'value': 'Line Printer Daemon',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'lighttpd HTTP Server Detection':          {   'value': 'lighttpd',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'VMware vSphere Detect':                   {   'value': 'VMware vSphere',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'VMware vCenter Detect':                   {   'tag': 'plugin_output',
                                                                're': 'VMware\s+vCenter\s+Server\s+([0-9\. a-zA-Z-]+)',
                                                                'prefix': 'VMware vCenter ',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'SLP Server Detection (TCP)':              {   'value': 'SLP Server',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'SLP Server Detection (UDP)':              {   'value': 'SLP Server',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'RPC portmapper (TCP)':                    {   'value': 'RPC portmapper',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'RPC portmapper Service Detection':        {   'value': 'RPC portmapper',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'MySQL Server Detection':                  {   'tag': 'plugin_output',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'prefix': 'MySQL ',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Samba Version':                           {   'tag': 'plugin_output',
                                                                're': 'Version\s+is\s+:\s+(Samba [0-9\.]+)',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Flexera FlexNet Publisher Detection':     {   'tag': 'plugin_output',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'prefix': 'Flexera FlexNet Publisher ',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Microsoft Outlook Web Access (OWA) Version Detection':     {   'tag': 'plugin_output',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'prefix': 'Outlook Web Access ',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Dell Integrated Remote Access Controller (iDRAC) Detection':     {   'tag': 'plugin_output',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'prefix': 'iDRAC ',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Webmin Detection':                        {   'tag': 'plugin_output',
                                                                'prefix': 'Webmin ',
                                                                're': 'Webmin version\s+:\s+([0-9\.]+)',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Sendmail Service Detection':              {   'tag': 'plugin_output',
                                                                'prefix': 'Sendmail ',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Retrospect Client Detection':             {   'tag': 'plugin_output',
                                                                'prefix': 'Retrospect ',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'ManageEngine ServiceDesk Plus Detection': {   'tag': 'plugin_output',
                                                                'prefix': 'ManageEngine ServiceDesk ',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Apple TV Version Detection':              {   'tag': 'plugin_output',
                                                                're': 'Model\s+:\s+([a-zA-Z0-9\.,-]+)',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Apple TV Detection':                      {   'value': 'Apple TV',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'VNC HTTP Server Detection':               {   'value': 'VNC Server',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Zabbix Web Interface Detection':          {   'value': 'Zabbix',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'WS-Management Server Detection':          {   'value': 'WS-Management Server',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'SolarWinds Orion Product Detection':      {   'value': 'SolarWinds Orion',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Session Initiation Protocol Detection':   {   'value': 'sip',
                                                                'key': 'service',
                                                                'yields': 'services.service'},
                 'Samba Web Administration Tool (SWAT) Detection':   {   'value': 'Samba Web Admin',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'BACnet Protocol Detection':               {   'value': 'BACnet',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'Microsoft Exchange Server Detection (Uncredentialed)':   {   'value': 'MS Exchange',
                                                                'key': 'service',
                                                                'yields': 'services.service'},
                 'QNAP QTS/QES/QuTS hero - Web Detection':  {   'value': 'QNAP QTS',
                                                                'key': 'software',
                                                                'yields': 'services.software'},
                 'EMC Legato Networker Detection':          {   'value': 'EMC Legato Networker',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'Erlang Port Mapper Daemon Detection':     {   'value': 'Erlang Port Mapper',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'HPE Intelligent Management Center dbman Detection':     {   'value': 'HPE iMC dbman',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'Pervasive PSQL / Btrieve Server Detection': { 'value': 'Pervasive PSQL / Btrieve',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'PaperCut MF Detection':                   {   'value': 'PaperCut MF',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'Plone Detection':                         {   'value': 'Plone',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'RIP Detection':                           {   'value': 'RIP Router',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'Intel Management Engine Active Management Technology (AMT) Remote Access Enabled':  {   'value': 'Intel AMT Remote Access',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'Apache Shiro HTTP Detection':             {   'value': 'Apache Shiro',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'Microsoft System Center Configuration Manager Management Point Detection':  {   'value': 'SCCM Management Point',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'SAP BusinessObjects Business Intelligence Platform Web Detection.':  {   'value': 'SAP BusinessObjects',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 'Crystal Reports Central Management Server Detection':  {   'value': 'Crystal Reports Central Management Server',
                                                                'key': 'software',
                                                                'yields': 'softwares.service'},
                 #'Universal Plug and Play (UPnP) Protocol Detection':   {   'tag': 'plugin_output',
                 #                                               'key': 'web_dir_enum',
                 #                                               're': '(https?://[a-z0-9\.:\/-]+\.xml)',
                 #                                               'yields': 'services.web_dir_enum'},
                 'Synology DiskStation Manager (DSM) Detection':  { 'tag': 'plugin_output',
                                                                'key': 'software',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'prefix': 'Synology DSM ',
                                                                'yields': 'services.software'},
                 'H3C / HP Intelligent Management Center Detection': { 'tag': 'plugin_output',
                                                                'key': 'software',
                                                                'prefix': 'HP Intelligent Management Center ',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'yields': 'services.software'},
                 'Dell OpenManage Server Administrator Detection': { 'tag': 'plugin_output',
                                                                'key': 'software',
                                                                'prefix': 'Dell OpenManage ',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'yields': 'services.software'},
                 'HP System Management Homepage Detection': {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                'prefix': 'HP System Management ',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'yields': 'services.software'},
                 'HP Integrated Lights-Out (iLO) Detection': {  'tag': 'plugin_output',
                                                                'key': 'os',
                                                                'prefix': 'HP iLO ',
                                                                're': 'Generation\s+:\s+([0-9\.]+)',
                                                                'yields': 'hosts.os'},
                 'Squid Proxy Version Detection':           {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'prefix': 'Squid Proxy ',
                                                                'yields': 'services.software'},
                 'SNMP Supported Protocols Detection':      {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                're': 'SNMP\s+version\s+(SNMPv[0-9a-z]+)',
                                                                'yields': 'services.software'},
                 'HTTP Server Type and Version':            {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                're': 'web server type is\s+:[\s\n\r]+([a-zA-Z0-9\s\/.-]+)',
                                                                'yields': 'services.software'},
                 'Sophos XG Firewall Detection':            {   'tag': 'plugin_output',
                                                                'key': 'software',
                                                                'prefix': 'Sophos XG ',
                                                                're': 'Version\s+:\s+([0-9\.]+)',
                                                                'yields': 'services.software'},
                 'Open Network Video Interface Forum (ONVIF) Protocol Detection': { 'tag': 'plugin_output',
                                                                'key': 'web_dir_enum',
                                                                're': '(Endpoint:\s+.+$)',
                                                                'yields': 'services.web_dir_enum'},
                 #'SSL Service Requests Client Certificate': {   'value': 'Client cert required',
                 #                                               'key': 'software',
                 #                                               'yields': 'services.software'},
                 'Web Application Potentially Sensitive CGI Parameter Detection':    {   'tag': 'plugin_output',
                                                                'key': 'sensitive_param',
                                                                'yields': 'services.sensitive_param'}}

informational_as_issue = {  'Missing or Permissive Content-Security-Policy frame-ancestors HTTP Response Header',
                            'Missing or Permissive X-Frame-Options HTTP Response Header',
                            #'HTTP Methods Allowed (per directory)',
                            'NFS Server Superfluous',
                            'RPC Services Enumeration',
                            'HSTS Missing From HTTPS Server',
                            'DNS Server Version Detection',
                            'TCP Port 0 Open: Possible Backdoor',
                            'Web Site Client Access Policy File Detection',
                            'Web Server Office File Inventory',
                            'Universal Plug and Play (UPnP) Protocol Detection',
                            #'SSH SHA-1 HMAC Algorithms Enabled',
                            "SSL Certificate 'commonName' Mismatch",
                            'Web Application Cookies Not Marked HttpOnly',
                            'SSL Certificate Signed Using SHA-1 Algorithm',
                            #'SSH Protocol Versions Supported',
                            #'SSH Password Authentication Accepted',
                            #'SSH SHA-1 HMAC Algorithms Enabled',
                            'Web Server Unconfigured - Default Install Page Present',
                            'Microsoft Windows SMB Versions Supported (remote check)',
                            'SSL/TLS Recommended Cipher Suites',
                            'SMTP Authentication Methods',
                            'Web Server Directory Enumeration',
                            'WebDAV Directory Enumeration',
                            'SNMP Query System Information Disclosure',
                            "HTTP Cookie 'secure' Property Transport Mismatch",
                            'Microsoft Windows SMB NativeLanManager Remote System Information Disclosure',
                            'Server Message Block (SMB) Protocol Version 1 Enabled (uncredentialed check)',
                            'Windows NetBIOS / SMB Remote Host Information Disclosure',
                            'Microsoft SQL Server UDP Query Remote Version Disclosure',
                            'SSL Cipher Block Chaining Cipher Suites Supported',
                            'LDAP Crafted Search Request Server Information Disclosure',
                            'SSL Certificate with no Subject',
                            'HTTP Proxy Open Relay Detection',
                            'HTTP Proxy CONNECT Request Relaying',
                            'HTTP Proxy Open gopher:// Request Relaying',
                            'SSL Certificate with no Common Name',
                            'SNMP Query Routing Information Disclosure',
                            'VNC Server Unencrypted Communication Detection',
                            'TeamViewer remote detection',
                            'Web Server UPnP Detection',
                            'Web Application Cookies Not Marked Secure' }

ignore_plugins = {  'Asset Attribute: Fully Qualified Domain Name (FQDN)',
                    'Common Platform Enumeration (CPE)',
                    'VNC Server Security Type Detection',
                    'VNC Software Detection',
                    'IPMI Versions Supported',
                    'IMAP Service Banner Retrieval',
                    'IMAP Service STARTTLS Command Support',
                    'RMI Registry Detection',
                    'JQuery Detection',
                    'HTTP Methods Allowed (per directory)',
                    'Nessus Scan Information',
                    'SSL Certificate Chain Not Sorted',
                    'Device Type',
                    'SSH Algorithms and Languages Supported',
                    'SSH Server Type and Version Information',
                    'SSL Cipher Block Chaining Cipher Suites Supported',
                    'TLS Version 1.0 Protocol Detection',
                    'TLS Version 1.1 Protocol Detection',
                    'Telnet Server Detection',
                    'TFTP Daemon Detection',
                    'OpenSSL Detection',
                    'External URLs',
                    'Nessus Windows Scan Not Performed with Admin Privileges',
                    'Network Time Protocol (NTP) Server Detection',
                    'COM+ Internet Services (CIS) Server Detection',
                    'LDAP Server Detection',
                    'TLS Version 1.2 Protocol Detection',
                    'HyperText Transfer Protocol (HTTP) Information',
                    'Microsoft Windows SMB Service Detection',
                    'Terminal Services Use SSL/TLS',
                    'TLS ALPN Supported Protocol Enumeration',
                    'Target Credential Status by Authentication Protocol - No Credentials Provided',
                    'OS Identification',
                    'OS Security Patch Assessment Not Available',
                    'Microsoft Windows SMB Registry : Nessus Cannot Access the Windows Registry',
                    'DCE Services Enumeration',
                    'Ping the remote host',
                    'Traceroute Information',
                    'TCP/IP Timestamps Supported',
                    'SSL Perfect Forward Secrecy Cipher Suites Supported',
                    'SSL Cipher Suites Supported',
                    'SSL Root Certification Authority Certificate Information',
                    'SSL / TLS Versions Supported',
                    'Local Checks Not Enabled (info)',
                    'Microsoft Windows SMB2 and SMB3 Dialects Supported (remote check)',
                    'Service Detection',
                    'Microsoft SQL Server TCP/IP Listener Detection',
                    'Microsoft SQL Server STARTTLS Support',
                    'SSL Certificate Chain Contains Certificates Expiring Soon',
                    'ICMP Timestamp Request Remote Date Disclosure',
                    'WMI Not Available',
                    'Kerberos Information Disclosure',
                    'DNS Server Detection',
                    'CGI Generic Tests Load Estimation',
                    'CGI Generic Tests Load Estimation (all tests)',
                    'Windows Terminal Services Enabled',
                    'Web Server Uses Basic Authentication over HTTPS',
                    'SSH Password Authentication Accepted',
                    'SSH SHA-1 HMAC Algorithms Enabled',
                    'MSSQL Host Information in NTLM SSP',
                    'Protected Web Page Detection',
                    'Microsoft Windows NTLMSSP Authentication Request Remote Network Name Disclosure',
                    'HyperText Transfer Protocol (HTTP) Redirect Information',
                    'HTTP Host Information via NTLM SSP over HTTP(S)',
                    'SSL Certificate Expiry - Future Expiry',
                    'Strict Transport Security (STS) Detection',
                    'Service Detection (HELP Request)',
                    'MSRPC Service Detection',
                    # potentially interesting
                    'SSL Service Requests Client Certificate',
                    'SSL/TLS Service Requires Client Certificate',
                    'NetBIOS Multiple IP Address Enumeration',
                    'nginx HTTP Server Detection', # to get version
                    'Patch Report', # list of missing patches for the host
                    # end
                    'SMTP Server Detection',
                    'SMTP Service STARTTLS Command Support',
                    'SMTP Host Information in NTLM SSP',
                    'SolarWinds Orion Web Performance Monitor (WPM) Remote Detection',
                    'Unknown Service Detection: Banner Retrieval',
                    'Ethernet MAC Addresses',
                    'Web Application Cookies Are Expired',
                    'Ethernet Card Manufacturer Detection',
                    'Service Detection (GET request)',
                    'TLS Version 1.3 Protocol Detection',
                    'HTTP/2 Cleartext Detection',
                    'jQuery UI Detection',
                    'Non-compliant Strict Transport Security (STS)',
                    'Backported Security Patch Detection (SSH)',
                    'Backported Security Patch Detection (PHP)',
                    'FTP Server Detection',
                    'FTP Service AUTH TLS Command Support',
                    'VMware ESX/GSX Server detection',
                    'iSCSI Target Detection',
                    'TLS Next Protocols Supported',
                    'SSL Session Resume Supported',
                    'SSL Certificate Signed Using Weak Hashing Algorithm (Known CA)',
                    'Alert Standard Format / Remote Management and Control Protocol Detection',
                    'Apache Banner Linux Distribution Disclosure',
                    'Backported Security Patch Detection (WWW)',
                    'SNMP Protocol Version Detection',
                    'SNMP Request Network Interfaces Enumeration',
                    'IPMI Cipher Suites Supported',
                    'OS Identification and Installed Software Enumeration over SSH v2 (Using New SSH Library)',
                    'Authenticated Check : OS Name and Installed Package Enumeration',
                    'DNS Server BIND version Directive Remote Version Detection',
                    'DNS Server hostname.bind Map Hostname Disclosure',
                    'TLS NPN Supported Protocol Enumeration',
                    'Unix Operating System on Extended Support',
                    'Samba Server Detection',
                    'OS Identification Failed',
                    'OpenSSH Detection',
                    'NFS Share Export List',
                    'Backported Security Patch Detection (SMTP)',
                    'Web Site Cross-Domain Policy File Detection',
                    'RDP Screenshot',
                    'SMTP Server Connection Check',
                    'SSL Certificate Chain Contains Unnecessary Certificates',
                    'LDAP Service STARTTLS Command Support',
                    'LDAP Group Enumeration',
                    'LDAP User Enumeration',
                    'mDNS Detection (Local Network)',
                    'Remote Desktop Protocol Service Detection',
                    'Apple AirPlay Web Detection',
                    'RTMP Server Detection',
                    'SLP Find Attributes',
                    'Apple iTunes Music Sharing Enabled',
                    'Apple Filing Protocol Server Detection',
                    'UltraVNC Java Viewer Detection',
                    'Microsoft Message Queuing Detection',
                    'DNS Server DNSSEC Aware Resolver',
                    'DNS Sender Policy Framework (SPF) Enabled',
                    'OpenSSL Version Detection',
                    'Splashtop Streamer remote detection',
                    'Microsoft Windows SMB LanMan Pipe Server Listing Disclosure',
                    'Host Fully Qualified Domain Name (FQDN) Resolution' }
